networks:
  cstar-net:

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    # Use socat in the devcontainer container so that the IDE "Ports" has a
    # process it can use to show that the database is running.
    command: >
      bash -c "
        apt-get update && apt-get install -y socat &&
        socat TCP-LISTEN:5432,fork,reuseaddr TCP:postgres:5432 &
        sleep infinity
      "
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cstar-net
    volumes:
      - ../..:/workspaces:cached

  postgres:
    container_name: cstar_postgres
    environment:
      POSTGRES_DB: tmsdb
      POSTGRES_USER: tms
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      interval: 5s
      retries: 5
      test: ['CMD-SHELL', 'pg_isready -U tms -d tmsdb']
      timeout: 5s
    image: postgres:15.12-bookworm
    networks:
      - cstar-net
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
